[package]
name = "visualize_replay_buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
takzero.workspace = true
fast-tak.workspace = true
rand.workspace = true
# image = "0.25.1"

[lints]
workspace = true
